server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Essa é a linha mágica que resolve o 404 no Angular
    location / {
        try_files $uri $uri/ /index.html;
    }
}