spring:
  application:
    name: noemare-api

  # 👉 Jackson: Formatação de datas para o padrão brasileiro
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    time-zone: America/Sao_Paulo

  datasource:
    # URL apontando para o Render com sslmode=require (obrigatório para acesso externo)
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6guuc0gjchc73cedd10-a.oregon-postgres.render.com/noemare?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:jair_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:CImdW3kO88iq2I2UH5uwfyIZOoDtgoGH}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

api:
  security:
    token:
      secret: ${JWT_SECRET:minha-chave-ultra-secreta-do-noemare}
      # 28800000 milissegundos = 8 horas
      expiration: ${JWT_EXPIRATION:28800000}
    
    # 👉 NOVO: Código mestre para registro de Admins (Lido da variável MASTER_CODE)
    master-code: ${MASTER_CODE:@ADMIN-NOEMARE-MASTER-2026@}

app:
  cors:
    # Origens permitidas: Tenta ler do ambiente, senão usa os IPs de dev
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://10.0.0.128:4200}